### ISSUE TITLE
Callbacks to Haskell code cause segfault

### ISSUE THREAD

**Issue by albertov** [mitchty/alpine-linux-ghc-bootstrap#16]
Hi,

It seems that calling a wrapped callback to haskell code from C causes a segfault. GHC 8.0.1 on other linux platforms doesn't seem to have this issue. The following program should reproduce the problem:

Save as `proba.hs`:

``` haskell
{-# LANGUAGE ForeignFunctionInterface #-}                                                        

import Foreign.C.Types
import Foreign.Ptr

main :: IO () 
main = do                                                                                        
  f <- wrapIt (\c -> print "hola" >> return (c*c))                                               
  print f 
  c_callMe f
  freeHaskellFunPtr f

foreign import ccall safe "callMe"                                                               
  c_callMe :: FunPtr (CDouble -> IO CDouble) -> IO ()                                            

foreign import stdcall safe "wrapper"                                                            
  wrapIt :: (CDouble -> IO CDouble) -> IO (FunPtr (CDouble -> IO CDouble))   
```

Save as `c_proba.c``

``` c
#include <stdio.h>

typedef double (*callback)(double n);                                                            

void callMe(callback fun)
{   
  printf("%lx\n", fun);
  double n= 34.2;
  printf("The number is: %f", fun(n));
}   
```

Build:

``` sh
ghc -o proba proba.hs c_proba.c
```

Disable PAX protection (else GRSEC will kill it since the callback is created in the heap by the RTS):

``` sh
paxctl -Cpemrxs proba
```

And execute:

``` sh
./proba
```

Output on my system:

```
0x0000000000b1bf48
b1bf48
Segmentation fault (core dumped)
```

Note that the pointer address is correctly passed to C, interestingly the stack trace shows this address is being called twice (the last call causing the segfault)

``` sh
gdb -c core
(.....)
(gdb) bt
#0  0x0000000000b1bf48 in ?? ()
#1  0x000000000040a229 in ?? ()
#2  0x404119999999999a in ?? ()
#3  0x0000000000b1bf48 in ?? ()
#4  0x0000000000b17bd8 in ?? ()
#5  0x404119999999999a in ?? ()
#6  0x0000000200005350 in ?? ()
#7  0x0000000000409b9e in ?? ()
#8  0x000000000086b1c0 in ?? ()
#9  0x0000000000000000 in ?? ()
```

**Comment by albertov** [comment]
Adding this line before making GHC fixes it:

``` sh
sed -i 's,chmod,sed -i s/__gnu_linux__/1/ libffi/build/src/closures.c \&\& chmod,' libffi/ghc.mk
```

(stolen from https://github.com/nilcons/ghc-musl/blob/master/ghc-musl/Dockerfile#L24)

**Comment by mitchty** [comment]
Let me try building an updated ghc with that in place and see if it gets corrected and if so I'll update everything. Thanks for finding the bug and fix as well!

**Comment by albertov** [comment]
Great. Thanks for all your work creating these packages, they're extremely useful to us!

**Comment by mitchty** [comment]
Ok it seems to work:

```
/tmp # ghc -o proba proba.hs c_proba.c
c_proba.c: In function 'callMe':

c_proba.c:7:10: error:
     warning: format '%lx' expects argument of type 'long unsigned int', but argument 2 has type 'callback {aka double (*)(double)}' [-Wformat=]
       printf("%lx\n", fun);
              ^
[1 of 1] Compiling Main             ( proba.hs, proba.o )

proba.hs:16:1: warning: [-Wunsupported-calling-conventions]
    • the 'stdcall' calling convention is unsupported on this platform,
      treating as ccall
    • When checking declaration:
        foreign import stdcall safe "wrapper" wrapIt
          :: (CDouble -> IO CDouble) -> IO (FunPtr (CDouble -> IO CDouble))
Linking proba ...
/tmp # ./proba
0x00007feda3d55018
7feda3d55018
"hola"
```

If you could validate, this is the repos/ghc I used:

```
/tmp # cat /etc/apk/repositories 
http://dl-cdn.alpinelinux.org/alpine/v3.4/main
http://dl-cdn.alpinelinux.org/alpine/v3.4/community
https://mitchty.net/ghc/8.0.1
/tmp # apk info ghc
ghc-8.0.1-r1 description:
The Glasgow Haskell Compiler

ghc-8.0.1-r1 webpage:
http://haskell.org

ghc-8.0.1-r1 installed size:
336377856

ghc-8.0.1-r0 description:
The Glasgow Haskell Compiler

ghc-8.0.1-r0 webpage:
http://haskell.org

ghc-8.0.1-r0 installed size:
316139520


```

I'll remove the r0 version on s3 but it'll be basically this r1 version when I migrate things to s3 (rsync is faster for quick checks).

**Comment by albertov** [comment]
Yep, the GHC from https://mitchty.net/ghc/8.0.1 no longer has this issue. I'll close this.

However, there's another problem when running Alpine's GRSEC kernel. I'll open a new ticket for it.
